# environment.yml: Mandatory dependencies only.
channels:
- conda-forge
- nodefaults
dependencies:
- pip
- numpy
- scipy
- netcdf4
- matplotlib
- basemap
- qt
- pyqt
- cftime=1.4.1
- pip:
  - pyjnius
  - seawater
  - thredds-crawler
  - sphinx_rtd_theme
